### ISSUE TITLE
Deficiencies in WebIDL

### ISSUE THREAD

**Issue by domenic** [w3ctag/jsidl#2]
Doing spec reviews, here are the major deficiencies I've noticed:
- Bad support for plain old JavaScript objects ("dictionaries"):
  - Cannot return them from attributes
  - Cannot easily signify that the same object is returned each time, possibly with mutated properties
  - They're not as easy to create or manipulate as classes ("interfaces"), leading to the creation of inheritance hierarchies of non-constructible classes.
- Encourages no constructors
  - If you want something non-constructible, you should do this by adding a "secret" argument to the constructor, and giving only the browser code access to the correct secret. That is, it should be a manual and painful process.
  - In general, there should not be a way to create instances of a class via IDL without using the constructor. This will force spec authors to create constructors encapsulating all the relevant behavior (or use the secret-based behavior as above).
- Lack of "macro" ability, to be compatible with duck-typing. E.g. two classes that have very similar APIs, with a few differences, often cause spec authors to set up an inheritance hierarchy in order to share definitions between them, even though there is no relevant is-a relationship. In normal JS, these would often be just two distinct classes with same-named methods and properties. The ability to say "inline these X properties and methods here" would help allow this.
- Lack of stratification into the internal-layer and the exposed-layer. ES does this with internal slots. For example, there are sometimes complaints about making a property mutable, because then the C++ code will crash because of broken invariants. The C++ code should not be consulting public properties of an object! The public properties should only be reflecting the internal layer.

**Comment by annevk** [comment]
We have far more pressing issues. Such as lack of an ArrayBuffer story, lack of proper arrays, etc. It's not even possible at the moment to express certain things. Aesthetics can wait.

**Comment by domenic** [comment]
Although I appreciate you're coming at it from the perspective of missing features, I don't think it's fair to characterize these things as aesthetics. I think I tried very hard to drive at the serious problems underlying each point and how they prevent you from building reasonable APIs.

Now, issues like `get x` vs. `readonly attribute x`, or `ToString x` vs. `DOMString x`, are definitely in the "aesthetic" and "can wait" categories.

**Comment by bzbarsky** [comment]
Thank you for putting this together.

I agree the dictionary support is suboptimal.  Gecko has some extensions to allow returning them from attributes if the return value is guaranteed cached-until-cleared similar to sicking's array proposals.  I would be in favor of extending WebIDL to do that obviously.

The mutated properties bit is harder.  WebIDL currently doesn't have any way to "update" a dictionary in the sense of taking a WebIDL dictionary and a JS object and mutating the latter to match the former.  It would be interesting to do that.

On the other hand, for a getter it's not clear whether it's better to mutate in-place or create a new object.  Again, this is similar to the array discussion.

The "macro" ability is there, as far as I can tell: you define an interface with the shared members and have both of your interfaces implement it.  I agree it could be more generic (e.g. being able to share some state like that across an interface and a dictionary used as an argument to the interface is a common request).

The stratification (and in particular definition of internal slots) is left to spec prose.  WebIDL doesn't say anything about where values come from.  I agree that some spec authors could be lazy and just set up one object that they both use internally and hand out to consumers.  I'd be interested in concrete examples of this (HTMLInputElement.files?) before trying to define a WebIDL way to avoid these situations, because I don't have a good feel for when this issue comes up.

I think the issue Anne raises is an important one also, and similar to your concern with dictionaries.  It comes down to not having great integration with the moving-target nature of ES6.  There are no good ways in WebIDL right now to talk about manipulating ES objects like typed arrays, Maps, Sets, and yes Objects and Arrays.  I'm not sure whether we can come up with a general facility that will pick up new things, somehow or need to do ad-hoc things as we go...  If the latter, are the various internal slot names in ES6 at least stable?  Because in practice either WebIDL or specs using these objects (e.g. array buffer views) or both will need to reference those internal slots.

**Comment by domenic** [comment]
> The "macro" ability is there, as far as I can tell: you define an interface with the shared members and have both of your interfaces implement it.

I am guessing I misunderstand interfaces then: doesn't this create an inheritance hierarchy (observable via `Object.getPrototypeOf`)?

>  I'd be interested in concrete examples of this (HTMLInputElement.files?) before trying to define a WebIDL way to avoid these situations, because I don't have a good feel for when this issue comes up.

Good call, thanks.

> If the latter, are the various internal slot names in ES6 at least stable? Because in practice either WebIDL or specs using these objects (e.g. array buffer views) or both will need to reference those internal slots.

I think they're pretty close to stable in all cases by now, yes. I can definitely see how this has been a moving target over the last year or two now. But I can't imagine anything changing with regard to the internal slots these days, except perhaps in the module and realm APIs.

**Comment by bzbarsky** [comment]
> doesn't this create an inheritance hierarchy (observable via Object.getPrototypeOf)

No, it does not.  If `A implements B` that means is that all the methods/properties declared in B are copied onto `A.prototype`.  And if `C implements B`, then `C.prototype` gets a copy of them too.  In fact, we even decided that in that situation, if `foo` is a method on B, then `A.prototype.foo` and `C.prototype.foo` are distinct objects, so it really does act like a macro.

You can still shoot yourself in the foot slightly by forgetting to put `[NoInterfaceObject]` on B, which will cause `window.B` to exist when it's not needed.  And as you discovered it's not obviously discoverable...

**Comment by domenic** [comment]
@annevk pointed out a minor missing feature: an easy way to refer to "initial values" of globals. E.g. in ES you would do this by defining per-realm intrinsics like %Promise% or %PromisePrototype% and using them. A less formal, but probably sufficient, approach would be to say something like "using the initial value of the Promise constructor for this realm" (or, s/realm/top-level browsing context).

IDL needs some kind of phrase like that you can link to a `<dfn>` of.

**Comment by cynthia** [comment]
We are no longer actively looking into this, although I believe @tobie might be interested in following up on this inside WebIDL though.
